import argparse
import asyncio
import os

import pandas as pd
from bs4 import BeautifulSoup
from playwright.async_api import async_playwright

from src.io.path_definition import get_project_dir

# --------------------------------
# Helper: chunk list into batches
# --------------------------------
def chunk_list(data, size):
    """Yield successive sublists of fixed size from a list.

    This utility function is used to split a long list of URLs into smaller
    batches for concurrent processing.

    Args:
        data (list): The list to be chunked.
        size (int): The maximum number of items per chunk.

    Yields:
        list: A sublist containing up to ``size`` elements.
    """

    for i in range(0, len(data), size):
        yield data[i:i + size]


# --------------------------------
# Scrape a single URL (async)
# --------------------------------
async def fetch(browser, url):
    """Scrape a single URL using Playwright and extract specific court fields.

    The function loads the target page, waits for key DOM selectors, and uses
    BeautifulSoup to parse the HTML content for elements such as:
    - Related laws
    - Judgment content
    - Historical judgment records

    Timeout for each selector is 10 seconds; missing sections are logged and
    returned as empty strings.

    Args:
        browser (playwright.async_api.Browser): A Playwright browser instance.
        url (str): The webpage URL to scrape.

    Returns:
        dict: A dictionary with the following keys:
            - ``歷審裁判``: Historical judgment records.
            - ``相關法條``: Related laws.
            - ``裁定``: Judgment HTML content.
            - ``url``: The scraped URL.
    """

    page = await browser.new_page()
    await page.goto(url, wait_until="load")

    rela_law_activation = False

    try:
        await page.wait_for_selector("ul.rela-law li", timeout=10000)
        rela_law_activation = True
    except Exception:
        print(f"Timeout while waiting for ul.rela-law in {url}")

    htmlcontent_activation = False

    try:
        await page.wait_for_selector("div.htmlcontent", timeout=10000)
        htmlcontent_activation = True
    except Exception:
        print(f"Timeout while waiting for div.htmlcontent in {url}")

    judhis_activation = False

    try:
        await page.wait_for_selector("#JudHis", timeout=10000)
        judhis_activation = True
    except Exception:
        print(f"Timeout while waiting for JudHis in {url}")

    html = await page.content()
    await page.close()

    soup = BeautifulSoup(html, "html.parser")

    if rela_law_activation:
        related_law = ", ".join([li.get_text(strip=True) for li in soup.select("ul.rela-law li")])
    else:
        related_law = ""
    if htmlcontent_activation:
        htmlcontent = "".join([div.get_text(strip=True) for div in soup.select("div.htmlcontent")])
    else:
        htmlcontent = ""
    if judhis_activation:
        history = ", ".join([li.get_text(strip=True) for li in soup.select("#JudHis ul li")])
    else:
        history = ""

    return {"歷審裁判": history,
            "相關法條": related_law,
            "裁定": htmlcontent,
            "url": url}


# --------------------------------
# Wrapper with retry logic
# --------------------------------
async def fetch_with_retry(browser, url):
    """Fetch data from a URL with retry logic.

    Retries the ``fetch`` function up to a global ``RETRIES`` limit when an
    exception occurs. Each retry waits one second before continuing.

    Args:
        browser (playwright.async_api.Browser): Playwright browser instance.
        url (str): The target URL.

    Returns:
        dict: Scraped fields returned by ``fetch`` upon success.
              If all retries fail, returns:
              ``{"url": url, "error": "Failed after retries"}``
    """
    for attempt in range(1, RETRIES + 1):
        try:
            return await fetch(browser, url)
        except Exception as e:
            print(f"Retry {attempt}/{RETRIES} failed for {url}: {e}")
            await asyncio.sleep(1)
    return {"url": url, "error": "Failed after retries"}


# --------------------------------
# Process a batch concurrently
# --------------------------------
async def process_batch(browser, urls):
    """Process a batch of URLs concurrently with a semaphore.

    Each URL is processed by ``fetch_with_retry`` but limited by the global
    concurrency level (``CONCURRENCY``). All results are gathered using
    ``asyncio.gather``.

    Args:
        browser (playwright.async_api.Browser): Playwright browser instance.
        urls (list[str]): List of URLs in the current batch.

    Returns:
        list[dict]: A list of dictionaries generated by ``fetch_with_retry``.
    """

    semaphore = asyncio.Semaphore(CONCURRENCY)

    async def sem_task(url):
        async with semaphore:
            return await fetch_with_retry(browser, url)

    tasks = [sem_task(u) for u in urls]
    return await asyncio.gather(*tasks)


# --------------------------------
# Main execution
# --------------------------------
async def main(urls: list[str]):
    """Run the scraping pipeline in batches with concurrency control.

    This function orchestrates:
    - Launching the Playwright browser
    - Splitting input URLs into batches
    - Processing each batch concurrently
    - Collecting all scraping results

    Args:
        urls (list[str]): Full list of URLs to scrape.

    Returns:
        list[dict]: Combined scraping results from all batches.
    """
    all_results = []

    async with async_playwright() as playwright:
        browser = await playwright.chromium.launch(headless=True)
        for batch_index, url_batch in enumerate(chunk_list(urls, BATCH_SIZE), start=1):
            print(f"Processing batch {batch_index} ({len(url_batch)} urls)")

            batch_results = await process_batch(browser, url_batch)
            all_results.extend(batch_results)

            print(f"Batch {batch_index} done. Total collected: {len(all_results)}")

    print("All batches complete!")
    return all_results


# Run async main
if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument('--concurrency', type=int, default=2, help='同時處理的頁面數量')
    parser.add_argument('--batch_size', type=int, default=10, help='每個批次處理的 URL 數量')
    parser.add_argument('--date', type=str, help='判決書日期編號 民國年_月_日', required=True)
    parser.add_argument('--test', action='store_true', help="執行測試模式，只處理前 100 筆資料")

    args = parser.parse_args()

    BATCH_SIZE = args.batch_size  # 100 URLs per batch
    CONCURRENCY = args.concurrency # 20 pages open at the same time
    RETRIES = 3  # retry failed URLs

    file_path = os.path.join(get_project_dir(), "data", f"cases_{args.date}.csv")
    if not os.path.isfile(file_path):
        raise FileNotFoundError(f"File {file_path} not found")

    folder_processed = os.path.join(get_project_dir(), "data_processed")
    if not os.path.exists(folder_processed):
        os.makedirs(folder_processed)

    output_filepath = os.path.join(folder_processed, f"cases_processed_{args.date}.csv")

    if os.path.isfile(output_filepath):
        raise FileExistsError(f"File {output_filepath} already exists")

    df_raw = pd.read_csv(file_path, index_col=0)
    if args.test:
        df_raw = df_raw.head(10)
    all_urls = df_raw['url'].tolist()

    results = asyncio.run(main(urls=all_urls))

    df_output = pd.DataFrame(results)
    df_output = df_raw.merge(df_output, on="url", how="left")

    df_output.to_csv(output_filepath, index=False)

